[[plugins]] # 最近のファイルを表示# {{{
# なんかファイル開いた時（バッファが/.*/に一致）まで遅延
repo = 'Shougo/neomru.vim'
on_path = '.*'
# }}}

[[plugins]] # 入力補完# {{{
# lua必須、INSERTモードまで遅延
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1
# }}}

[[plugins]] # カレントディレクトリのツリー表示# {{{
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'Tr', 'Tree']
# }}}

[[plugins]] # markdown記述補助# {{{
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
# }}}

[[plugins]] # markdownプレビュー# {{{
repo = 'kannokanno/previm'
on_ft = 'markdown'
# }}}

[[plugins]] # CSV編集がいい感じに# {{{
repo = 'chrisbra/csv.vim'
on_ft = 'csv'
# }}}

[[plugins]] # tomlファイルのシンタックス# {{{
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}

[[plugins]] # html5のシンタックス# {{{
repo = 'othree/html5.vim'
on_ft = 'html'
# }}}

[[plugins]] # css3のシンタックス# {{{
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
# }}}

[[plugins]] # javascriptのシンタックス# {{{
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'
# }}}

# vim: fdm=marker
